# Generated by Django 5.2.9 on 2026-01-03 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='name',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='roll',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='stream',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
