# Generated by Django 5.2.9 on 2026-01-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_studentdata_email_studentdata_name_studentdata_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='teacher_present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='teacher_total_days',
            field=models.IntegerField(default=0),
        ),
    ]
